"""upgrade storage

Revision ID: 9e3f3ba02ecb
Revises: d867b0fa81f2
Create Date: 2024-04-22 11:59:40.762028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3f3ba02ecb'
down_revision: Union[str, None] = 'd867b0fa81f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('total_quantity', sa.Integer(), nullable=True))
    op.add_column('storage', sa.Column('avg_price', sa.Float(), nullable=True))
    op.add_column('storage', sa.Column('remain', sa.Integer(), nullable=True))
    op.drop_column('storage', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('storage', 'remain')
    op.drop_column('storage', 'avg_price')
    op.drop_column('storage', 'total_quantity')
    # ### end Alembic commands ###
